# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23a4fdcad6fb0181e520522f3870c5d56c0d7a4595045ae7691908848bf576661c8619fe80d0356fd58a1a04003ba06b4406543bda4106b6ad824efcfbc8c664

test:
  secret_key_base: d577e1758d663160a4190465ef4b4618cf9cb8cd258bed967e7b34e557db63a8a0434e905c47e3bad16016b862586cab6f7458d877f81e3565b28b0b44443f2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
